name: unit tests

on:
  push:
    branches: "**"

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: test build instructions on ubuntu
      run: docker build -f scripts/compile-test/Ubuntu .
    - name: run unit tests
      run: docker run $(docker image ls -q | head -n 1) bash -c "cd hotspot/build/ && make test"
