name: test build instructions

on:
  push:
    branches: "**"

jobs:
  test-ubuntu-2004:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: compile
      run: docker build -t hotspot-build-ubuntu20.04 -f scripts/compile-test/Ubuntu20.04 .
    - name: run unit tests
      run: docker run hotspot-build-ubuntu20.04 bash -c "cd hotspot/build/ && ctest --output-on-failure -j \$(nproc) -E tst_perfdata"
  
  test-ubuntu-2204:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: compile
      run: docker build -t hotspot-build-ubuntu22.04 -f scripts/compile-test/Ubuntu22.04 .
    - name: run unit tests
      run: docker run hotspot-build-ubuntu22.04 bash -c "cd hotspot && ctest --preset dev-asan -j \$(nproc)"

  test-archlinux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: compile
      run: docker build -t hotspot-build-archlinux -f scripts/compile-test/Archlinux .
    - name: run unit tests
      run: docker run hotspot-build-archlinux bash -c "cd hotspot && ctest --preset dev-asan -j \$(nproc)"

  test-fedora:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: compile
      run: docker build -t hotspot-build-fedora -f scripts/compile-test/Fedora .
    - name: run unit tests
      run: docker run hotspot-build-fedora bash -c "cd hotspot/build/ && ctest --output-on-failure -j \$(nproc)"

  test-opensuse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: compile
      run: docker build -t hotspot-build-opensuse -f scripts/compile-test/OpenSuse .
    - name: run unit tests
      run: docker run hotspot-build-opensuse bash -c "cd hotspot/build/ && ctest --output-on-failure -j \$(nproc)"
